sudo: required

language: java

services:
- docker

before_install:
- docker pull clockercentral/clocker
- docker run -d -P clockercentral/clocker
#- docker run -d -v ~/.brooklyn:/root/.brooklyn -v ~/.ssh:/root/.ssh -P clockercentral/clocker

script:
- ls -al
