sudo: required

language: java

services:
- docker

before_install:
- sudo service docker restart ; sleep 10
- chmod 600 brooklyn.properties
- docker run -d --name=host1 -e ROOT_PASS="root" tutum/ubuntu:trusty
- docker run -d --name=host2 -e ROOT_PASS="root" tutum/ubuntu:trusty
- docker run -d --name=host3 -e ROOT_PASS="root" tutum/ubuntu:trusty
- docker run -d --name=brooklyn --link host1 --link host2 --link host3 -p 8081:8081 -v `pwd`/brooklyn.properties:/root/.brooklyn/brooklyn.properties --entrypoint bin/brooklyn.sh googlielmo/clocker launch
- docker ps -a
- docker inspect brooklyn
- ps auxw
- /sbin/ifconfig
- /sbin/netstat -an

install:
- travis_wait mvn install -DskipTests=true -X

script:
- echo OK

cache:
  directories:
  - $HOME/.m2
