sudo: required

services:
  - docker

before_install:
- docker pull clockercentral/clocker
- docker run -d -v ~/.brooklyn:/root/.brooklyn -v ~/.ssh:/root/.ssh -P clockercentral/clocker jclouds:softlayer:lon02 calico

